### ISSUE TITLE
Captcha not getting created at first load

### ISSUE THREAD

**Issue by 8ib** [infinity-next/infinity-next#235] opened 2016-01-20 08:39 UTC
As soon as you reload the page however, it creates the captcha successfully.

I think it might have something to do with this, running php artisan migrate produces this error:
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'c
  lient_ip' used in key specification without a key length (SQL: alter table
  `captcha` add index `captcha_client_ip_index`(`client_ip`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'c
  lient_ip' used in key specification without a key length

Page with the captcha on the initial load:
select * from `captcha` where (`cracked_at` is null and `created_at` >= '2016-01-20 08:06:41') and `client_ip` = 'xxx.xxx.xx.xxx' order by `created_at` desc limit 1

insert into `captcha` (`client_ip`, `solution`, `profile`, `hash`, `created_at`) values ('xxx.xxx.xx.xxx', 'KUEG', 'default', '[BINARY DATA]', '2016-01-20 08:11:41')

Is there anyway to know if it's our configuration that is the problem?

Thanks!!

**Comment by Graham--M** [comment] 2016-02-08 14:17
I can confirm this issue. I've not found what causes it yet but the image has a link to `.png` when it should have a link to `{hash}.png`.

**Comment by jaw-sh** [comment] 2016-02-11 07:00
I can reproduce. This is an issue with infinity-next/brennan-captcha though.

**Comment by milezteg** [comment] 2016-02-11 07:57
Can we assume you're going to have to replace infinity-next/brennan-captcha ?

**Comment by jaw-sh** [comment] 2016-02-11 08:07
I may end up cloning the repo. I don't know how to handle the copyright, 
because while every line of code has changed and has been rewritten by 
me, the conceptual algorithm used to generate the image that breaks 
machine reading was taught to me by him. The first draft of code was 
also his, but everything after came from me.

I'm going to have to email a legal specialist but in short there's no 
reason why I can't use it because 1) it's its own thing, 2) it's agpl. 
It's a pedantic concern. I'm also not tempted to change too much because 
it'd show a gross amount of ill will on my part.

**Comment by jaw-sh** [comment] 2016-02-11 15:07
Fixed with e6401fd0d312517659bf733ebc7c0e68d4e30cfc.
Please make sure your packagist package is infinity-next/laravel-captcha now.

**Closed by jaw-sh** 2016-02-11 15:07 UTC
