### ISSUE TITLE
laravel bullshit rewrite rules LOL

### ISSUE THREAD

**Issue by rajlaksh** [infinity-next/infinity-next#127] opened 2015-10-04 17:24 UTC
You Laravel Config is Wrong

Laravel Config for Nginx is

`location / {
    try_files $uri $uri/ /index.php?$query_string;
}` only.

**Comment by jaw-sh** [comment] 2015-10-04 17:26
Duplicate of #116. Someone else contributed that a while ago and I never checked up on it.

**Closed by jaw-sh** 2015-10-04 17:26 UTC

**Comment by rajlaksh** [comment] 2015-10-04 17:28
Here is Mini Version of Nginx for it,

`server {`
`listen 80;`
`server_name 	example.com;`

`root 			/var/www/public;`
`index 			index.php index.htm index.html;`

`location / {`
`try_files $uri $uri/ /index.php?$query_string;`
`}`

`location ~ .php$ {`
`fastcgi_pass 127.0.0.1:9000;`
`fastcgi_index index.php;`
`fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;`
`include fastcgi_params;`
`}`

}`
