### ISSUE TITLE
Error upon the execution of "php artisan db:seed"

### ISSUE THREAD

**Issue by QuakersOat** [infinity-next/infinity-next#181] opened 2015-12-02 00:47 UTC
Here's a paste of the error(s):
 [Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update
  a child row: a foreign key constraint fails (`infinity`.`role_permissions`,
   CONSTRAINT `role_permissions_role_id_foreign` FOREIGN KEY (`role_id`) REFE
  RENCES `roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: inser
  t into `role_permissions` (`role_id`, `permission_id`, `value`) values (1,
  board.create, 1))

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update
  a child row: a foreign key constraint fails (`infinity`.`role_permissions`,
   CONSTRAINT `role_permissions_role_id_foreign` FOREIGN KEY (`role_id`) REFE
  RENCES `roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE)

And here's a screenshot:
![](https://u.pomf.io/caddov.png)
I'm using php 5.6.11, MySQL 5.6.27, and nginx 1.9.3
I hope this is all the information you need. I see that others have had this problem, but seemingly not with mysql. Thanks!

**Comment by jaw-sh** [comment] 2015-12-02 00:49
The database seeder will be dysfunctional until after the migration 
scripts are written. They are in a partially complete state because of 
ongoing work that required me to commit uniquely adjusted scripts.

Once 8chan needs to set up Next I'll also be fixing the seeder.

**Comment by QuakersOat** [comment] 2015-12-02 01:53
Cool stuff you're doing here. I wish the best to you folks.

**Comment by interjection** [comment] 2015-12-04 23:55
As a stop-gap solution you can simply checkout commit `18256c5601ada8e5a94467136889bd24a47e69fd`, run the migrations, seed the database, and then finally checkout master and migrate forward.

**Comment by QuakersOat** [comment] 2015-12-05 06:50
Alright, that seemed to work, except that both before and after migrating forward, I get this error:
Whoops, looks like something went wrong.

1/1
ReflectionException in Container.php line 737:
Class view does not exist
in Container.php line 737
at ReflectionClass->__construct('view') in Container.php line 737
at Container->build('view', array()) in Container.php line 627
at Container->make('view', array()) in Application.php line 674
at Application->make('Illuminate\Contracts\View\Factory') in Container.php line 1159
at Container->offsetGet('Illuminate\Contracts\View\Factory') in RoutingServiceProvider.php line 144
at RoutingServiceProvider->Illuminate\Routing\{closure}(object(Application), array()) in Container.php line 734
at Container->build(object(Closure), array()) in Container.php line 627
at Container->make('Illuminate\Contracts\Routing\ResponseFactory', array()) in Application.php line 674
at Application->make('Illuminate\Contracts\Routing\ResponseFactory', array()) in helpers.php line 61
at app('Illuminate\Contracts\Routing\ResponseFactory') in helpers.php line 578
at response() in Handler.php line 69
at Handler->render(object(Request), object(ErrorException)) in Kernel.php line 281
at Kernel->renderException(object(Request), object(ErrorException)) in Kernel.php line 91
at Kernel->handle(object(Request)) in index.php line 54
![](https://u.pomf.io/ladvcj.png)

**Comment by weja** [comment] 2015-12-07 22:53
So any idea when this will happen..? This is completely unusable now.

**Comment by jaw-sh** [comment] 2015-12-07 22:55
I cannot take time to repair the seeder until after 8chan's migration to the software.

**Comment by weja** [comment] 2015-12-07 22:56
Ok, I haven't really followed what's the situation with 8chan.. But thanks.

**Comment by jaw-sh** [comment] 2015-12-12 18:55
Marking this as Keystone because it needs to be fixed with the migration scripts.

**Comment by weja** [comment] 2015-12-15 13:06
Issue in this post is fixed, but it gives another about site options.. Doing fresh install. Posting works now though.

**Comment by jaw-sh** [comment] 2015-12-15 13:07
Exact errors would be extraordinary helpful ...

**Comment by weja** [comment] 2015-12-15 13:46
Sorry, I was on mobile so I couldn't do it.. I thought someone else already had reported the error. Here's the error:

  [Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`infn`.`site_settings`, CONSTRAI
  NT `site_settings_option_name_foreign` FOREIGN KEY (`option_name`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: inser
  t into `site_settings` (`option_value`, `option_name`) values (1024, 0))


  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`infn`.`site_settings`, CONSTRAI
  NT `site_settings_option_name_foreign` FOREIGN KEY (`option_name`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by jaw-sh** [comment] 2015-12-15 13:56
I don't know. The issue is caused on line 33 of `database/OptionSeeder.php`. The option is created, and then it attempts to create a setting with default value if it was just made. In your instance, the primary key `option_name` is set to `0` for that option, which should never happen. In PostgreSQL, it works fine. I'll look into it more later.

**Comment by weja** [comment] 2015-12-15 14:07
Is it easy to convert from PGSQL to mySQL later if I go with PGSQL now? Or so I need wipe then? Thanks for quick reply.

**Comment by jaw-sh** [comment] 2015-12-15 14:11
I've never done a conversion. PGSQL is probably better in general, though, and will receive priority support because 8chan uses it. If you don't have a specific reason to use MySQL it may be a better idea to just adjust to PgSQL.

**Comment by jaw-sh** [comment] 2015-12-15 14:12
Sorry, I hate telling people to just swap software, but it's the easiest thing atm.

**Comment by weja** [comment] 2015-12-15 14:14
Alright, I perfectly understand. I can study PGSQL.

**Closed** 2016-06-01 05:13 UTC
Labels: bug, database, keystone
